export const defaultServices = [
  {
    id: 1,
    category: "main",
    title: "Nadi Pariksha",
    description:
      "A non-invasive Ayurvedic pulse diagnosis technique used by our practitioners to assess your doshas and identify imbalances, serving as the starting point for your personalized wellness journey.",
    image: "/images/ser-1.jpg",
    rating: 4.9,
    benefits: [
      "Identifies dosha imbalance through pulse reading",
      "Supports personalized therapy and diet planning",
      "Helps detect early wellness patterns",
      "Non-invasive and comfortable assessment",
    ],
    sort_order: 1,
    is_active: true,
  },
  {
    id: 2,
    category: "main",
    title: "Panchakarma Rituals",
    description:
      "A comprehensive Ayurvedic detoxification and cleansing program designed to eliminate deep-seated toxins and effectively restore balance to the body and mind.",
    image: "/images/ser-2.jpg",
    rating: 4.9,
    benefits: [
      "Supports deep detoxification and cleansing",
      "Helps restore digestion and metabolic balance",
      "Promotes lightness, energy, and clarity",
      "Personalized rituals guided by Ayurvedic assessment",
    ],
    sort_order: 2,
    is_active: true,
  },
  {
    id: 3,
    category: "main",
    title: "Marma Chikitsa",
    description:
      "An Ayurvedic technique involving gentle stimulation of specific vital energy points on the body to improve energy flow, reduce stress, and support deep healing.",
    image: "/images/ser-3.jpg",
    rating: 4.8,
    benefits: [
      "Activates vital energy points",
      "Helps reduce stress and body tension",
      "Supports natural healing and energy flow",
      "Encourages relaxation and emotional balance",
    ],
    sort_order: 3,
    is_active: true,
  },
  {
    id: 4,
    category: "main",
    title: "Osteopathic Therapy",
    description:
      "A manual therapy focused on the body's musculoskeletal system, aiming to improve overall health by strengthening the framework of the body and managing pain.",
    image: "/images/ser-4.jpg",
    rating: 4.8,
    benefits: [
      "Improves musculoskeletal alignment",
      "Helps manage stiffness and chronic pain",
      "Supports posture, mobility, and flexibility",
      "Gentle hands-on care for whole-body function",
    ],
    sort_order: 4,
    is_active: true,
  },
  {
    id: 5,
    category: "main",
    title: "Ozone Therapy",
    description:
      "An advanced restorative treatment utilized to address various chronic conditions and enhance overall systemic vitality through the healing properties of ozone.",
    image: "/images/ser-5.jpg",
    rating: 4.7,
    benefits: [
      "Supports systemic vitality and recovery",
      "Helps improve oxygen utilization",
      "May assist chronic wellness concerns",
      "Complements integrative restorative care plans",
    ],
    sort_order: 5,
    is_active: true,
  },
  {
    id: 6,
    category: "main",
    title: "Meru Therapy",
    description:
      "A specialized therapy deeply focused on spinal health and alignment, aiming to restore harmony and balance to the body's structural and energetic systems.",
    image: "/images/ser-6.jpg",
    rating: 4.8,
    benefits: [
      "Supports spinal health and alignment",
      "Helps ease back, neck, and shoulder discomfort",
      "Encourages structural and energetic balance",
      "Promotes improved movement and body awareness",
    ],
    sort_order: 6,
    is_active: true,
  },
  {
    id: 7,
    category: "main",
    title: "Craniosacral Therapy",
    description:
      "A gentle, hands-on technique that monitors the rhythm of cerebrospinal fluid to release tensions deep in the body, relieving pain and dysfunction.",
    image: "/images/ser-7.jpg",
    rating: 4.8,
    benefits: [
      "Gently releases deep body tension",
      "Supports nervous system relaxation",
      "May help reduce pain and dysfunction",
      "Encourages calm, sleep, and inner ease",
    ],
    sort_order: 7,
    is_active: true,
  },
  {
    id: 8,
    category: "main",
    title: "Pain Management Therapies",
    description:
      "Integrative treatments combining classical and contemporary therapies, including L&B pain management, to address chronic discomfort and restore natural mobility.",
    image: "/images/heal/manual.png",
    rating: 4.9,
    benefits: [
      "Targets chronic discomfort and stiffness",
      "Supports natural mobility and functional movement",
      "Combines classical and contemporary therapies",
      "Personalized approach for pain relief goals",
    ],
    sort_order: 8,
    is_active: true,
  },
];

export const defaultTestimonials = [
  {
    id: 1,
    name: "Anusha Rajan",
    review:
      "A deeply soothing and authentic experience. Netra Tejas felt gentle yet remarkably effective, bringing clarity and comfort in the most natural way. A refined approach to non-invasive care that truly delivers.",
    sort_order: 1,
    is_active: true,
  },
  {
    id: 2,
    name: "Muthukrishnan Gopal",
    review:
      "An exceptional destination for authentic Ayurvedic care. The experience is thoughtfully curated, offering both depth and genuine healing in a calm, welcoming environment.",
    sort_order: 2,
    is_active: true,
  },
  {
    id: 3,
    name: "Meera Venkatesh",
    review:
      "What stood out was the level of personalisation. Beginning with Nadi Pariksha, every therapy felt aligned to my body's needs. The experience was unhurried, intuitive, and deeply restorative.",
    sort_order: 3,
    is_active: true,
  },
  {
    id: 4,
    name: "Rohit Subramanian",
    review:
      "From Abhyanga to relaxation therapies, each session brought a noticeable sense of lightness and ease. The care extended to every member of the family, making it a truly holistic experience.",
    sort_order: 4,
    is_active: true,
  },
  {
    id: 5,
    name: "Priya Narayanan",
    review:
      "I arrived seeking relief, but discovered something far more profound, a sense of stillness. Therapies like Shirodhara brought a quiet calm that stayed long after the session ended. A space where healing feels effortless",
    sort_order: 5,
    is_active: true,
  },
];

export const defaultNadiCamps = [
  {
    id: 1,
    doctor: "Dr. K Aravindhan",
    camp_date: "20/05/2026",
    location: "Chennai, Tamil Nadu",
    contact: "Manickam M (9444004975)",
    address: "Gurukripa Agencies, No : 16, Aadhi Street , Villivakkam",
    sort_order: 1,
    is_active: true,
  },
  {
    id: 2,
    doctor: "Dr. S Meenakshi",
    camp_date: "15/05/2026",
    location: "Pondicherry",
    contact: "Saravanan (9843210987)",
    address: "Sri Auro Wellness Hall, Heritage Town",
    sort_order: 2,
    is_active: true,
  },
  {
    id: 3,
    doctor: "Dr. R Rajesh",
    camp_date: "05/05/2026",
    location: "Coimbatore, Tamil Nadu",
    contact: "Vijay (9765432109)",
    address: "Art of Living Center, Race Course",
    sort_order: 3,
    is_active: true,
  },
  {
    id: 4,
    doctor: "Dr. N Lakshmi",
    camp_date: "10/06/2026",
    location: "Salem, Tamil Nadu",
    contact: "Prakash (9123456789)",
    address: "Shiva Temple Premise, Fairlands",
    sort_order: 4,
    is_active: true,
  },
  {
    id: 5,
    doctor: "Dr. V Anitha",
    camp_date: "22/05/2026",
    location: "Trichy, Tamil Nadu",
    contact: "Ramesh (9876543210)",
    address: "Srirangam Community Hall",
    sort_order: 5,
    is_active: true,
  },
  {
    id: 6,
    doctor: "Dr. M Karthik",
    camp_date: "02/05/2026",
    location: "Tirunelveli, Tamil Nadu",
    contact: "Gopal (9944332211)",
    address: "Nellai Wellness Hub",
    sort_order: 6,
    is_active: true,
  },
  {
    id: 7,
    doctor: "Dr. P Swathi",
    camp_date: "18/05/2026",
    location: "Vellore, Tamil Nadu",
    contact: "Suresh (9000011122)",
    address: "Anna Salai Center",
    sort_order: 7,
    is_active: true,
  },
];

export const defaultRelaxationTherapies = [
  {
    id: 1,
    category: "relax",
    title: "Abhyanga",
    duration: "45 mins",
    short_description: "An Ayurvedic massage that promotes wellbeing by applying warm oil on your entire body.",
    details:
      "Experience the benefits of Abhyanga, an Ayurvedic massage that promotes wellbeing by applying warm oil on your entire body. The oil is the central component of Abhyanga. When combined with massage strokes, it promotes overall health and wellness. It can be done by a therapist or self-administered at home.",
    benefits: [
      "Reduces the signs of aging",
      "Gives the body muscle tone & energy",
      "Gives the limbs a firmness",
      "Lubricates the joints",
      "Promotes blood circulation & detoxification",
      "Activates the body's internal organs",
      "Boosts endurance",
      "Calms the nerves",
      "Softens & smoothens skin",
    ],
    image: "/images/relax/abhyanga.png",
    sort_order: 1,
    is_active: true,
  },
  {
    id: 2,
    category: "relax",
    title: "Uzhichil",
    duration: "45 mins",
    short_description: "Effective full-body, deep tissue ayurvedic massage therapy with specific oil pressure.",
    details:
      "This is one of the most effective full-body, deep tissue ayurvedic massage therapy. Pressure is applied to the specific parts of the body with oil massage. This therapy is highly recommended for blood circulation as well as the nervous system.",
    benefits: [
      "Reduces pressure on the heart",
      "Treats nervous disorders",
      "Calms anxiety",
      "Good for insomnia & hypertension",
      "Relieves stress & headaches",
    ],
    image: "/images/relax/uzhichil.png",
    sort_order: 2,
    is_active: true,
  },
  {
    id: 3,
    category: "relax",
    title: "Reflexology",
    duration: "30 mins",
    short_description: "Pressure-point therapy for the feet to treat illnesses and strengthen body systems.",
    details:
      "Your foot is rubbed, pressed and squeezed on certain locations to treat illnesses. And when the entire foot is massaged, all of the body's systems is strengthened.",
    benefits: [
      "Provides deep relaxation",
      "Improves sleep quality",
      "Energizes all organs & body tissues",
      "Relieves anxiety & stress",
      "Enhances blood circulation in the lower half of the body",
      "Strengthens the feet",
      "Reduces stiffness & tiredness",
    ],
    image: "/images/relax/foot.png",
    sort_order: 3,
    is_active: true,
  },
  {
    id: 4,
    category: "relax",
    title: "Shirolepa",
    duration: "45 mins",
    short_description: "Soothing application of medicinal pastes on the scalp for psychosomatic relief.",
    details:
      "Medicinal pastes are applied over the entire scalp which is soothing and has relaxing properties. This time-tested Ayurveda therapy is an excellent treatment for a variety of psychosomatic ailments and boosting overall well-being.",
    benefits: [
      "Improves sleep quality",
      "Helps the visionary abilities",
      "When combined with yoga, it helps with anxiety",
      "Improves hair health",
      "Brings the pita dosh back into equilibrium",
    ],
    image: "/images/relax/shirolepa.png",
    sort_order: 4,
    is_active: true,
  },
  {
    id: 5,
    category: "relax",
    title: "Body Wrap",
    duration: "90 mins",
    short_description: "Natural aromatic body wrap enriched with Moringa for detoxification and nourishment.",
    details:
      "Also called Haritaka Lepam, this beauty treatment is enriched with Moringa's goodness. This Ayurveda body wrap is a natural aromatic paste of freshly ground Moringa Oleifera leaves. It offers powerful antioxidants to skin cells to keep the skin cleansed, moisturized, nourished and revitalized naturally.",
    benefits: [
      "Detoxifies the skin",
      "Improves circulation",
      "Rejuvenates & hydrates the skin",
      "Improves skin tone",
      "Is soothing, comforting & provides relaxation",
    ],
    image: "/images/relax/chlorophyll.png",
    sort_order: 5,
    is_active: true,
  },
  {
    id: 6,
    category: "relax",
    title: "Shirodhara",
    duration: "45 mins",
    short_description: "Lukewarm oil stream over the forehead to enhance the central nervous system.",
    details:
      "A deeply relaxing therapy during which the scalp and forehead are caressed by a thin stream of medicated lukewarm oil. Helps to enhance the functioning of the central nervous system. Prevents hair fall and premature greying. Good for insomnia, tension headaches, nervous disorders. Shirodhara is a more calm therapeutic head massage that has many positive effects on the body and the mind. Shirodhara is therefore superior than a head massage. After applying oil to the forehead, there is a brief massage performed in this procedure. And it really is as soothing as it sounds.",
    benefits: [
      "Activates intuition",
      "Improves sleep",
      "Reduces stress",
      "Soothes eyes",
      "Pacifies elevated vata dosha",
      "Improves cognitive abilities",
    ],
    image: "/images/relax/shirodhara.png",
    sort_order: 6,
    is_active: true,
  },
  {
    id: 7,
    category: "relax",
    title: "Head Massage",
    duration: "45 mins",
    short_description: "Holistic treatment targeting marma points to boost healing and sleep quality.",
    details:
      "Ayurveda head massage is a holistic treatment that involves applying mild pressure to the head, which has 31 marma points where arteries and veins intersect. This massage also benefits the scalp. Besides, it boosts the body's natural healing abilities and enhances sleep quality.",
    benefits: [
      "Boosts blood circulation",
      "Induces relaxation & deep sleep",
      "Stimulates hair growth",
      "Improves concentration",
      "Relieves stress, insomnia, depression & migraine pain",
    ],
    image: "/images/relax/head-massage.png",
    sort_order: 7,
    is_active: true,
  },
  {
    id: 8,
    category: "relax",
    title: "Head & Foot Massage",
    duration: "45 mins",
    short_description: "Combined therapy for cerebral nourishment and reflex point activation.",
    details:
      "Head massage helps to break down muscular knots and reduces chronic neck & shoulder discomfort. This procedure also promotes hair growth, nourishes cerebral arteries, and enhances blood circulation. Foot massage, on the other hand, concentrates on the reflex points in the feet to enhance blood circulation. This practice, in addition to giving relaxation, is beneficial to one's vision because foot massage nourishes our optic nerve.",
    benefits: [
      "Advances hair growth",
      "Nourishes the brain's arteries",
      "Improves blood circulation",
      "Relaxes the body",
      "Nourishes the optic nerve",
    ],
    image: "/images/relax/head-foot.png",
    sort_order: 8,
    is_active: true,
  },
  {
    id: 9,
    category: "relax",
    title: "Keshavarna",
    duration: "45 mins",
    short_description: "Hair care treatment with crushed herbs and oils to prevent dandruff and boost growth.",
    details:
      "This hair care treatment involves an energizing head massage, which is enhanced with freshly crushed herbs, butter and olive oil. This treatment encourages healthy hair development and aids with dandruff prevention.",
    benefits: [
      "Promotes healthy hair growth",
      "Helps in eradicating dandruff",
      "Releases stress & anxiety",
    ],
    image: "/images/relax/keshavarna.png",
    sort_order: 9,
    is_active: true,
  },
  {
    id: 10,
    category: "relax",
    title: "Mukhalepa",
    duration: "45 mins",
    short_description: "Natural Ayurveda facial therapy for skin purity, glow, and rejuvenation.",
    details:
      "An Ayurveda Facial Therapy which uses natural ingredients, freshly ground herbal blends & packs to maintain the purity of one's inner beauty. Besides - fruits, coconut extract and saffron - all form part of this herbal paste. This beauty therapy is relaxing due to the fragrant and aromatic oils used. This natural herbal beauty therapy is by far the best solution for our outer cosmetic skin requirements, bringing out our inner glow.",
    benefits: [
      "Keeps skin soft, glowing & radiant",
      "Natural & chemical free",
      "Reduces acne & pimples",
      "Prevents aging of the skin",
      "Moisturises & hydrates",
      "Improves skin tone",
    ],
    image: "/images/relax/mukhalepa.png",
    sort_order: 10,
    is_active: true,
  },
];
