export const adminSections = [
  {
    id: "dashboard",
    href: "/admin/dashboard",
    label: "Dashboard",
    shortLabel: "Dashboard",
    eyebrow: "Booking Dashboard",
    title: "Booking calendar dashboard",
    description: "Monitor booking counts by day, review status totals, and inspect the booking load from a calendar view.",
    group: "Booking Engine",
  },
  {
    id: "inquiries",
    href: "/admin/inquiries",
    label: "Enquiries",
    shortLabel: "CRM",
    eyebrow: "Admin CRM",
    title: "Contact enquiries",
    description: "Review website contact and lead enquiries, update status, and keep the response queue moving.",
    group: "Operations",
  },
  {
    id: "bookings",
    href: "/admin",
    label: "Bookings",
    shortLabel: "Bookings",
    eyebrow: "Booking Engine",
    title: "Therapy bookings",
    description: "Review booking requests, assign therapists, and update booking status from the backend.",
    group: "Booking Engine",
  },
  {
    id: "services",
    href: "/admin/services",
    label: "Services",
    shortLabel: "Services",
    eyebrow: "Content API",
    title: "Service cards",
    description: "Manage service records that are served to the frontend from the backend API.",
    group: "Content API",
  },
  {
    id: "testimonials",
    href: "/admin/testimonials",
    label: "Testimonials",
    shortLabel: "Reviews",
    eyebrow: "Content API",
    title: "Page testimonials",
    description: "Manage category-based testimonials for home, relaxation, Nadi, and other public pages.",
    group: "Content API",
  },
  {
    id: "categories",
    href: "/admin/categories",
    label: "Categories",
    shortLabel: "Categories",
    eyebrow: "Content API",
    title: "Content categories",
    description: "Create, update, and organize category tabs used across service and therapy content.",
    group: "Content API",
  },
  {
    id: "nadi-camps",
    href: "/admin/nadi-camps",
    label: "Nadi Camps",
    shortLabel: "Nadi",
    eyebrow: "Content API",
    title: "Upcoming Nadi Camps",
    description: "Manage Nadi camp schedules, locations, contact details, and lifecycle status.",
    group: "Content API",
  },
  {
    id: "team",
    href: "/admin/team",
    label: "Team",
    shortLabel: "Team",
    eyebrow: "Team",
    title: "Therapists and doctor logins",
    description: "Manage therapist profiles and doctor login access together in one simple place.",
    group: "Team",
  },
  {
    id: "settings",
    href: "/admin/settings",
    label: "Settings",
    shortLabel: "Settings",
    eyebrow: "Admin Settings",
    title: "Email and SEO settings",
    description: "Configure booking and enquiry emails, customer acknowledgements, and page meta titles and descriptions.",
    group: "Settings",
  },
];

export const adminSectionIds = adminSections.map((section) => section.id);
export const adminSectionGroups = ["Operations", "Booking Engine", "Team", "Content API", "Settings"];
