export const adminSections = [
  {
    id: "dashboard",
    href: "/admin",
    label: "Overview",
    eyebrow: "Overview",
    title: "Enquiries and backend status",
    description: "Track incoming enquiries, response status, and content inventory from one place.",
  },
  {
    id: "services",
    href: "/admin/services",
    label: "Services",
    eyebrow: "Content",
    title: "Service cards",
    description: "Manage therapy and service cards for the public website.",
  },
  {
    id: "testimonials",
    href: "/admin/testimonials",
    label: "Testimonials",
    eyebrow: "Content",
    title: "Testimonials",
    description: "Keep reviews, ordering, and visibility updated.",
  },
  {
    id: "nadi-camps",
    href: "/admin/nadi-camps",
    label: "Nadi Camps",
    eyebrow: "Events",
    title: "Upcoming Nadi Camps",
    description: "Add camp schedules, doctors, locations, and contact details.",
  },
  {
    id: "relaxation-therapies",
    href: "/admin/relaxation-therapies",
    label: "Relax Therapies",
    eyebrow: "Therapies",
    title: "Relaxation therapies",
    description: "Control Abhyanga, Shirodhara, and other relaxation treatment cards.",
  },
  {
    id: "booking-slots",
    href: "/admin/booking-slots",
    label: "Booking Slots",
    eyebrow: "Bookings",
    title: "Therapy time slots",
    description: "Manage daily therapy availability, capacity, and active booking windows.",
  },
  {
    id: "therapists",
    href: "/admin/therapists",
    label: "Therapists",
    eyebrow: "Bookings",
    title: "Therapist roster",
    description: "Manage therapist profiles, specialties, and who is available for booking.",
  },
  {
    id: "therapist-schedules",
    href: "/admin/therapist-schedules",
    label: "Schedules",
    eyebrow: "Bookings",
    title: "Weekly therapist schedules",
    description: "Define recurring working hours, supported therapies, and slot capacities.",
  },
  {
    id: "therapist-blackouts",
    href: "/admin/therapist-blackouts",
    label: "Blackouts",
    eyebrow: "Bookings",
    title: "Leave and blackout dates",
    description: "Block full days or partial windows for therapist leave, events, and closures.",
  },
  {
    id: "bookings",
    href: "/admin/bookings",
    label: "Bookings",
    eyebrow: "Bookings",
    title: "Therapy bookings",
    description: "Review appointments, confirm sessions, and manage cancellations.",
  },
  {
    id: "alternative-treatments",
    href: "/admin/alternative-treatments",
    label: "Alt Treatments",
    eyebrow: "Therapies",
    title: "Alternative treatments",
    description: "Store the alternative therapy grid records for future frontend sync.",
  },
  {
    id: "panchakarma-core",
    href: "/admin/panchakarma-core",
    label: "PK Core",
    eyebrow: "Panchakarma",
    title: "Panchakarma core therapies",
    description: "Manage the five core Panchakarma entries and benefit lists.",
  },
  {
    id: "panchakarma-other",
    href: "/admin/panchakarma-other",
    label: "PK Other",
    eyebrow: "Panchakarma",
    title: "Panchakarma other treatments",
    description: "Maintain the supporting Panchakarma treatment list.",
  },
];

export const adminSectionIds = adminSections.map((section) => section.id);
