export const adminSections = [
  {
    id: "inquiries",
    href: "/admin/inquiries",
    label: "Enquiries",
    shortLabel: "CRM",
    eyebrow: "Admin CRM",
    title: "Contact enquiries",
    description: "Review website contact and lead enquiries, update status, and keep the response queue moving.",
    group: "Operations",
  },
  {
    id: "bookings",
    href: "/admin",
    label: "Bookings",
    shortLabel: "Bookings",
    eyebrow: "Booking Engine",
    title: "Therapy bookings",
    description: "Review booking requests, assign therapists, and update booking status from the backend.",
    group: "Booking Engine",
  },
  {
    id: "services",
    href: "/admin/services",
    label: "Services",
    shortLabel: "Services",
    eyebrow: "Content API",
    title: "Service cards",
    description: "Manage service records that are served to the frontend from the backend API.",
    group: "Content API",
  },
  {
    id: "team",
    href: "/admin/team",
    label: "Team",
    shortLabel: "Team",
    eyebrow: "Team",
    title: "Therapists and doctor logins",
    description: "Manage therapist profiles and doctor login access together in one simple place.",
    group: "Team",
  },
  {
    id: "relaxation-therapies",
    href: "/admin/relaxation-therapies",
    label: "Relax Therapies",
    shortLabel: "Relax",
    eyebrow: "Content API",
    title: "Relaxation therapies",
    description: "Manage relaxation therapy records that feed the frontend booking flow.",
    group: "Content API",
  },
];

export const adminSectionIds = adminSections.map((section) => section.id);
export const adminSectionGroups = ["Operations", "Booking Engine", "Team", "Content API"];
